// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl0oMu6G_xIekKlYadZUFhQbb_IZRpSQo',
    appId: '1:1031888638076:web:32220604deaee9958ef9f9',
    messagingSenderId: '1031888638076',
    projectId: 'notify-project-ddd2a',
    authDomain: 'notify-project-ddd2a.firebaseapp.com',
    storageBucket: 'notify-project-ddd2a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhwkbfkYk4zqHSgf_NM6ooXeGh_u29VZk',
    appId: '1:1031888638076:android:7eca8a2a76b140c28ef9f9',
    messagingSenderId: '1031888638076',
    projectId: 'notify-project-ddd2a',
    storageBucket: 'notify-project-ddd2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnz45AzeyGTx45sHt3-Z1tGLkTvfEm1tg',
    appId: '1:1031888638076:ios:3ecb0300fcc2cd7c8ef9f9',
    messagingSenderId: '1031888638076',
    projectId: 'notify-project-ddd2a',
    storageBucket: 'notify-project-ddd2a.appspot.com',
    iosBundleId: 'com.example.uplodeToCloudAndNoification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnz45AzeyGTx45sHt3-Z1tGLkTvfEm1tg',
    appId: '1:1031888638076:ios:3ecb0300fcc2cd7c8ef9f9',
    messagingSenderId: '1031888638076',
    projectId: 'notify-project-ddd2a',
    storageBucket: 'notify-project-ddd2a.appspot.com',
    iosBundleId: 'com.example.uplodeToCloudAndNoification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl0oMu6G_xIekKlYadZUFhQbb_IZRpSQo',
    appId: '1:1031888638076:web:89f513298c6c0c4b8ef9f9',
    messagingSenderId: '1031888638076',
    projectId: 'notify-project-ddd2a',
    authDomain: 'notify-project-ddd2a.firebaseapp.com',
    storageBucket: 'notify-project-ddd2a.appspot.com',
  );
}
